const GET_INGREDIENTS = 'GET_INGREDIENTS';
const SET_INGREDIENT = 'SET_INGREDIENT';
const ADD_INGREDIENT = 'ADD_INGREDIENT';
const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
const ADD_NAME = 'ADD_NAME';
const ADD_IMAGEURL = 'ADD_IMAGEURL';
const SET_TAGS = 'SET_TAGS';
const GET_TAGS = 'GET_TAGS';
const CREATE_TAG = 'CREATE_TAG';
const ADD_DESCRIPTION = 'ADD_DESCRIPTION';
const ADD_INSTRUCTIONS = 'ADD_INSTRUCTIONS';
const CREATE_RECIPE = 'CREATE_RECIPE';

export {
  GET_INGREDIENTS,
  SET_INGREDIENT,
  ADD_INGREDIENT,
  REMOVE_INGREDIENT,
  ADD_NAME,
  ADD_IMAGEURL,
  SET_TAGS,
  GET_TAGS,
  CREATE_TAG,
  ADD_DESCRIPTION,
  ADD_INSTRUCTIONS,
  CREATE_RECIPE
};
